easy_admin:

  user:
    display_name: true
    display_avatar: true
    name_property_path: 'username'
    avatar_property_path: 'avatar'
  formats:
    number: '%.00f'

  list:
    batch_actions: ['delete']

  design:
    assets:
      favicon: 'assets/backend/graph.png'
    menu:
      - label: 'Mon Profile'
        icon: 'user-circle-o'
        children:
          - { label: 'Afficher mon profil', route: fos_user_profile_show }
          - { label: 'Modifier email', route: fos_user_profile_edit }
          - { label: 'Changer mot de passe' , route: fos_user_change_password }
      - { entity: Restaurant }
      - { entity: User , permission: 'ROLE_SUPER_ADMIN' ,icon: 'users'}
      - { entity: Menu }
      - { entity: Commande }
      - { entity: MenuAction , permission: 'ROLE_SUPER_ADMIN'}
    
    brand_color: '#fe8001'
    
    rtl: false
  site_name: ' Administration'

  entities:
    Restaurant:
      class: App\Entity\Restaurant
#      controller: App\Controller\RestaurantController
      new:
        item_permission: 'ROLE_SUPER_ADMIN'
        title: 'Ajouter un restaurant'
        fields:
          - nom
          - description
          - adresse
          - telephone
          - horaire
          - administrateur
          - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.restaurant_images%',template: 'vich_uploader_image.html.twig' }
      form:
        form_options: { validation_groups: ['Default', 'my_validation_group'] }
        item_permission: 'ROLE_SUPER_ADMIN'
        fields:
          - nom
          - description
          - adresse
          - telephone
          - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.restaurant_images%' }
          - horaire
          - administrateur

      edit:
        title: 'Modifier restaurant'
        fields:
          - nom
          - description
          - adresse
          - telephone
          - horaire
          - administrateur
          - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.restaurant_images%'}

        list:
#          actions:
#            - { name: 'show', label: 'voir', icon: 'search' }
#            - { name: 'edit', label: 'modifier'}
#            - { name: 'delete', label: 'supprimer'}
          fields:
            - id
            - { property: 'image', type: 'image', base_path: '%app.path.restaurant_images%' }
            - nom
            - description
            - adresse
            - telephone
            - horaire
            - administrateur

    Menu:
      class: App\Entity\Menu
      new:
        title: 'Ajouter un menu'
        fields:
          - nom
          - detail
          - { property: 'prix' , type: 'money' ,  type_options: { currency: 'XOF' } }
          - typeMenu
          - etat
          - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.restaurant_images%',template: 'vich_uploader_image.html.twig' }
          - quantite
          - { property: 'restaurant' ,  }
      edit:
        title: 'Modifier un menu'
        fields:
          - nom
          - detail
          - prix
          - typeMenu
          - etat
          - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.restaurant_images%',template: 'vich_uploader_image.html.twig' }
          - quantite
          - restaurant
      list:
        actions:
          - { name: 'show', label: 'voir', icon: 'search' }
          - { name: 'edit', label: 'modifier' }
          - { name: 'delete', label: 'supprimer' }
        fields:
        - id
        - { property: 'image', type: 'image', base_path: '%app.path.restaurant_images%' }
        - nom
        - detail
        - prix
        - typeMenu
        - { property: 'etat', label: 'Disponibilite'}
        - quantite
        - restaurant
    
    User:
      icon: user
      label: Utilisateur
      class: App\Entity\User
      batch_actions: ['-delete']
      role: 'ROLE_SUPER_ADMIN'
      form:
        item_permission: 'ROLE_SUPER_ADMIN'
        fields:
          - username
          - email
          - password
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - phoneNumber
          - enabled
          - lastLogin
          - roles
      list:
        item_permission: 'ROLE_SUPER_ADMIN'
        actions:
          - { name: 'show', label: 'voir', icon: 'search' }
          - { name: 'edit', label: 'modifier'}
          - { name: 'delete', label: 'supprimer'}
        fields:
          - username
          - email
          - phoneNumber
          - enabled
          - lastLogin
          - roles

    Commande:
      label: Commande
      class: App\Entity\Commande
      list:
        actions:
          - { name: 'show', label: 'voir', icon: 'search' }
          - { name: 'edit', label: 'modifier' }
          - { name: 'delete', label: 'supprimer' }
        fields:
          - orderList
          - client
          - total
          - restaurant
      new:
        item_permission: 'ROLE_SUPER_ADMIN'
        fields:
          - orderList
          - client
          - total
          - restaurant

    MenuAction:
      class: App\Entity\MenuAction
      list:
        fields:
          - user
  