fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  service:
    mailer: fos_user.mailer.twig_swift
  from_email:
    address: dijatou26@gmail.com
    sender_name: Djiby Ndione
  registration:
    confirmation:
      template: '@FOSUser/Registration/email.txt.twig'
      enabled: true
  resetting:
    email:
      template: email/password_resseting.email.twig
      from_email:
        address: dijatou26@gmail.com
        sender_name: Djiby Ndione