gesdinet_jwt_refresh_token:
    ttl: 2592000
    user_identity_field: username
    ttl_update: true
    firewall: refresh
    token_parameter_name: refreshToken
    user_provider: fos_user.user_provider.username