vich_uploader:
    db_driver: orm

    mappings:
       restaurant_images:
           uri_prefix: /uploads/images/restaurant
           upload_destination: '%kernel.project_dir%/public/uploads/images/restaurant'
        # menu_images:
        #     uri_prefix: /uploads/images/menus
        #     upload_destinations: '%kernel.project_dir%/public/uploads/images/menus'